import { BRAND_TIER, LAYOUT_SCORE } from "./brands";
import { fmtPrice, fmtCompletion } from "@/lib/format";

const n = (v, unit, fallback = "—") => v != null ? `${v}${unit}` : fallback;
const nk = (v, unit) => v != null ? `${v.toLocaleString("ko-KR")}${unit}` : "—";

export const FIELD_META = {
  // ── 섹션1: 단지 개요 ──
  id: { label: "단지 ID", section: "개요", fmt: v => v ?? "—" },
  name: { label: "단지명", section: "개요", fmt: v => v ?? "—" },
  dong: { label: "동", section: "개요", fmt: v => v ?? "—" },
  gu: { label: "구/시", section: "개요", fmt: v => v ?? "—" },
  region: { label: "시/도", section: "개요", fmt: v => v ?? "—" },
  area: { label: "전용면적", section: "개요", unit: "㎡", fmt: v => n(v, "㎡") },
  price: { label: "분양가", section: "개요", unit: "만원", fmt: v => fmtPrice(v) },
  pp: { label: "평당가", section: "개요", unit: "만원", fmt: v => nk(v ?? 0, "만원") },
  floors: { label: "층수 범위", section: "개요", fmt: v => v ?? "—" },
  maxFloor: { label: "최고층", section: "개요", unit: "층", fmt: v => n(v, "층") },
  units: { label: "총세대수", section: "개요", unit: "세대", fmt: v => (v != null && v > 1) ? nk(v, "세대") : "정보 없음" },
  unsold: { label: "미분양 세대", section: "개요", unit: "세대", fmt: v => (v != null && v > 0) ? nk(v, "세대") : "—" },
  builder: { label: "시공사", section: "개요", fmt: (v) => { if (!v) return "—"; const b = BRAND_TIER[v]; return b ? `${v} (${b.tier})` : `${v} (기타)`; } },
  completion: { label: "입주예정", section: "개요", fmt: v => fmtCompletion(v) },
  layout: { label: "평면구조", section: "개요", fmt: (v) => { if (!v) return "—"; const sc = LAYOUT_SCORE[v]; return sc ? `${v} (${sc}점)` : v; } },
  heating: { label: "난방방식", section: "개요", fmt: v => v ?? "—" },
  address: { label: "지번 주소", section: "개요", fmt: v => v || "—" },
  roadAddress: { label: "도로명 주소", section: "개요", fmt: v => v || "—" },
  district: { label: "개발구역", section: "개요", fmt: v => v || "—" },
  avgMaintenanceCost: { label: "평균 관리비", section: "개요", unit: "만원", fmt: v => v != null && v > 0 ? `${v.toLocaleString("ko-KR")}만원` : "미수집" },
  primaryDirection: { label: "대표 향", section: "개요", fmt: v => v || "미수집" },
  // ── 섹션2: 가격/시장 ──
  nearbyMedian: { label: "주변 아파트 시세", section: "가격", unit: "만원", fmt: v => v ? nk(v, "만원") : "미수집", isEstimated: (v, apt) => apt?._fallbackNearbyMedian },
  jeonseRate: { label: "전세가율", section: "가격", unit: "%", fmt: v => n(v, "%"), isEstimated: (v, apt) => apt?._fallbackJeonseRate },
  pir: { label: "PIR (소득대비)", section: "가격", unit: "배", fmt: v => n(v, "배"), isEstimated: (v, apt) => apt?._fallbackPir },
  psr: { label: "PSR (주변대비)", section: "가격", fmt: v => typeof v === "number" ? v.toFixed(2) : "—", isEstimated: (v, apt) => apt?._fallbackPsr },
  dataReliability: { label: "데이터 신뢰도", section: "가격", unit: "%", fmt: v => n(v, "%"), isEstimated: (v, apt) => apt?._fallbackDataReliability },
  unsoldRate: { label: "미분양률", section: "가격", unit: "%", fmt: v => n(v, "%"), isDefault: v => v === 0, isEstimated: (v, apt) => apt?._fallbackUnsoldRate },
  recentTrades6m: { label: "최근6개월 거래", section: "가격", unit: "건", fmt: v => v != null ? `${v}건` : "미수집" },
  supplyRatio: { label: "공급비율", section: "가격", unit: "%", fmt: v => n(v, "%"), isEstimated: (v, apt) => apt?._fallbackSupplyRatio },
  builderCreditGrade: { label: "시공사 신용등급", section: "가격", fmt: v => v ?? "—" },
  builderDebtRatio: { label: "시공사 부채비율", section: "가격", unit: "%", fmt: v => n(v, "%"), isEstimated: (v, apt) => apt?._fallbackBuilderDebt },
  hugGuarantee: { label: "HUG 보증", section: "가격", fmt: v => v ? "있음" : "없음" },
  isRegulated: { label: "규제지역", section: "가격", fmt: v => v ? "예" : "아니오" },
  dsr40pass: { label: "DSR 40% 통과", section: "가격", fmt: v => v === true ? "통과" : v === false ? "미통과" : "—" },
  popGrowth: { label: "인구증감률", section: "가격", unit: "%", fmt: v => v != null ? `${v > 0 ? "+" : ""}${v}%` : "—" },
  nearbyBuildYear: { label: "주변 평균 건축연도", section: "가격", fmt: v => v != null ? `${v}년` : "미수집", isEstimated: (v, apt) => apt?._fallbackNearbyBuildYear },
  avgFloor: { label: "평균 거래 층수", section: "가격", unit: "층", fmt: v => v != null ? `${v}층` : "미수집", isEstimated: (v, apt) => apt?._fallbackAvgFloor },
  floorRange: { label: "거래 층수 범위", section: "가격", fmt: v => v ?? "미수집" },
  // ── 섹션3: 입지/교통/교육/환경 ──
  subwayDist: { label: "지하철 거리", section: "입지", unit: "m", fmt: v => v == null ? "—" : v >= 9000 ? "없음(9999)" : `${v}m`, isDefault: v => v === 9999 },
  busRoutes: { label: "버스 노선", section: "입지", unit: "개", fmt: v => n(v, "개") },
  icDist: { label: "IC 거리", section: "입지", unit: "km", fmt: v => n(v, "km") },
  ktxDist: { label: "KTX 거리", section: "입지", unit: "km", fmt: v => v == null ? "—" : v >= 9000 ? "없음(9999)" : `${v}km`, isDefault: v => v === 9999 },
  schoolScore: { label: "학군 점수", section: "입지", fmt: v => n(v, "점") },
  schoolGrade: { label: "학군 등급", section: "입지", fmt: v => v ?? "—" },
  hospital: { label: "병원", section: "입지", unit: "개", fmt: v => n(v, "개") },
  mart: { label: "대형마트", section: "입지", unit: "개", fmt: v => n(v, "개") },
  conv: { label: "편의점", section: "입지", unit: "개", fmt: v => n(v, "개") },
  park: { label: "공원", section: "입지", unit: "개", fmt: v => n(v, "개") },
  cafe: { label: "카페", section: "입지", unit: "개", fmt: v => n(v, "개") },
  culture: { label: "문화시설", section: "입지", unit: "개", fmt: v => n(v, "개") },
  bank: { label: "은행", section: "입지", unit: "개", fmt: v => n(v, "개") },
  pharmacy: { label: "약국", section: "입지", unit: "개", fmt: v => n(v, "개") },
  hospitalDist: { label: "병원 거리", section: "입지", unit: "m", fmt: v => v != null ? `${v}m` : "—" },
  martDist: { label: "마트 거리", section: "입지", unit: "m", fmt: v => v != null ? `${v}m` : "—" },
  convDist: { label: "편의점 거리", section: "입지", unit: "m", fmt: v => v != null ? `${v}m` : "—" },
  parkDist: { label: "공원 거리", section: "입지", unit: "m", fmt: v => v != null ? `${v}m` : "—" },
  view: { label: "조망", section: "입지", fmt: v => v ?? "—" },
  sunlight: { label: "일조", section: "입지", fmt: v => v ?? "—" },
  noise: { label: "소음", section: "입지", unit: "dB", fmt: v => n(v, "dB") },
  noxious: { label: "혐오시설", section: "입지", fmt: v => (v || []).length ? (v || []).join(", ") : "없음" },
  subwayName: { label: "최근접 지하철역", section: "입지", fmt: v => v || "—" },
  subwayLines: { label: "지하철 노선", section: "입지", fmt: v => v || "—" },
  busStopNames: { label: "주변 버스정류장", section: "입지", fmt: v => v ? v.split(",").slice(0, 5).join(", ") : "—" },
  // ── 섹션4: 상품성/건축 ──
  parkingRatio: { label: "주차 비율", section: "상품성", unit: "대/세대", fmt: v => n(v, "대/세대") },
  floorAreaRatio: { label: "용적률", section: "상품성", unit: "%", fmt: v => n(v, "%") },
  energyGrade: { label: "에너지 등급", section: "상품성", fmt: v => n(v, "등급") },
  greenBldg: { label: "녹색건축", section: "상품성", fmt: v => v || "미인증" },
  quakeDesign: { label: "내진설계", section: "상품성", fmt: v => v ? "적용" : "미적용" },
  exclusiveRatio: { label: "전용률", section: "상품성", unit: "%", fmt: v => n(v, "%") },
  hasPool: { label: "수영장", section: "상품성", fmt: v => v ? "있음" : "없음" },
  heatFuel: { label: "난방연료", section: "상품성", fmt: v => v || "미수집" },
  corridorType: { label: "복도유형", section: "상품성", fmt: v => v || "미수집" },
  buildingCoverageRatio: { label: "건폐율", section: "상품성", unit: "%", fmt: v => n(v, "%") },
  // ── 섹션5: 혜택/할인 ──
  discountPct: { label: "할인율", section: "혜택", unit: "%", fmt: v => n(v ?? 0, "%"), isDefault: v => v === 0 },
  loanFree: { label: "무이자 대출", section: "혜택", fmt: v => v ? "있음" : "없음" },
  loanFreePct: { label: "무이자 비율", section: "혜택", unit: "%", fmt: v => n(v ?? 0, "%"), isDefault: v => v === 0 },
  optionFree: { label: "옵션 무상", section: "혜택", fmt: v => v ? "있음" : "없음" },
  optionValue: { label: "옵션 가치", section: "혜택", unit: "만원", fmt: v => nk(v ?? 0, "만원"), isDefault: v => v === 0 },
  balconyFree: { label: "발코니 확장 무상", section: "혜택", fmt: v => v ? "있음" : "없음" },
  balconyValue: { label: "발코니 가치", section: "혜택", unit: "만원", fmt: v => nk(v ?? 0, "만원"), isDefault: v => v === 0 },
  cashback: { label: "캐시백", section: "혜택", unit: "만원", fmt: v => nk(v ?? 0, "만원"), isDefault: v => v === 0 },
  contractDiscount: { label: "계약금 할인", section: "혜택", fmt: v => v ? "있음" : "없음" },
  benefits: { label: "혜택 목록", section: "혜택", fmt: v => (v || []).length ? (v || []).join(", ") : "없음" },
  // ── 섹션6: 네이버 교차검증 ──
  naverNearbyMedian: { label: "네이버 주변 중위가", section: "교차검증", unit: "만원", fmt: v => v != null ? nk(v, "만원") : "미수집" },
  naverNearbyAvg: { label: "네이버 주변 평균가", section: "교차검증", unit: "만원", fmt: v => v != null ? nk(v, "만원") : "미수집" },
  naverJeonseRate: { label: "네이버 전세가율", section: "교차검증", unit: "%", fmt: v => v != null ? n(v, "%") : "미수집" },
  naverSellCount: { label: "매매 매물", section: "교차검증", unit: "건", fmt: v => v != null ? n(v, "건") : "미수집" },
  naverJeonseCount: { label: "전세 매물", section: "교차검증", unit: "건", fmt: v => v != null ? n(v, "건") : "미수집" },
  naverWolseCount: { label: "월세 매물", section: "교차검증", unit: "건", fmt: v => v != null ? n(v, "건") : "미수집" },
  naverBuildYear: { label: "네이버 평균 건축연도", section: "교차검증", fmt: v => v != null ? `${v}년` : "미수집" },
  naverAvgFloor: { label: "네이버 평균 층수", section: "교차검증", unit: "층", fmt: v => v != null ? `${v}층` : "미수집" },
  naverSchoolWalkMin: { label: "최근접 초등 도보", section: "교차검증", unit: "분", fmt: v => v != null ? n(v, "분") : "미수집" },
  naverNearbyCount: { label: "주변 단지 수", section: "교차검증", unit: "개", fmt: v => v != null ? n(v, "개") : "미수집" },
  naverFetchedAt: { label: "수집 시점", section: "교차검증", fmt: v => v ? new Date(v).toLocaleDateString("ko-KR") : "미수집" },
  // ── 섹션7: 미래가치 ──
  transitDev: { label: "교통 개발", section: "미래", fmt: v => v || "없음" },
  devDist: { label: "개발지 거리", section: "미래", unit: "km", fmt: v => v == null ? "—" : v >= 90 ? "없음" : `${v}km`, isDefault: v => v === 99 },
  cityDev: { label: "도시 개발", section: "미래", fmt: v => v || "없음" },
  industryDev: { label: "산업 개발", section: "미래", fmt: v => v || "없음" },
};

export const FIELD_SECTIONS = [
  { key: "개요", label: "단지 개요", fields: ["id","name","dong","gu","region","address","roadAddress","district","area","price","pp","floors","maxFloor","units","unsold","builder","completion","layout","heating","avgMaintenanceCost","primaryDirection"] },
  { key: "가격", label: "가격/시장 지표", fields: ["nearbyMedian","jeonseRate","pir","psr","dataReliability","nearbyBuildYear","avgFloor","floorRange"] },
  { key: "안전", label: "안전도/리스크", fields: ["unsoldRate","recentTrades6m","supplyRatio","builderCreditGrade","builderDebtRatio","hugGuarantee","isRegulated","dsr40pass","popGrowth"] },
  { key: "입지", label: "입지/교통/교육/환경", fields: ["subwayDist","subwayName","subwayLines","busRoutes","busStopNames","icDist","ktxDist","schoolScore","schoolGrade","hospital","hospitalDist","mart","martDist","conv","convDist","park","parkDist","cafe","culture","bank","pharmacy","view","sunlight","noise","noxious"] },
  { key: "상품성", label: "상품성/건축", fields: ["parkingRatio","floorAreaRatio","energyGrade","greenBldg","quakeDesign","exclusiveRatio","hasPool","heatFuel","corridorType","buildingCoverageRatio"] },
  { key: "혜택", label: "혜택/할인", fields: ["discountPct","loanFree","loanFreePct","optionFree","optionValue","balconyFree","balconyValue","cashback","contractDiscount","benefits"] },
  { key: "미래", label: "미래가치", fields: ["transitDev","devDist","cityDev","industryDev"] },
  { key: "교차검증", label: "네이버 교차검증", fields: ["naverNearbyMedian","naverNearbyAvg","naverJeonseRate","naverSellCount","naverJeonseCount","naverWolseCount","naverBuildYear","naverAvgFloor","naverSchoolWalkMin","naverNearbyCount","naverFetchedAt"] },
];
