export const UNSOLD = [
  // ── 서울 ──
  {
    id: "s1", name: "래미안 원펜타스", dong: "반포동", gu: "서초구", region: "서울",
    area: 84, price: 135000, pp: 5313, floors: "35~42층", maxFloor: 42,
    units: 641, unsold: 12, builder: "삼성물산", completion: "2026-12",
    subwayDist: 250, busRoutes: 30, icDist: 4, ktxDist: 15,
    schoolScore: 95, schoolGrade: "최우수",
    hospital: 8, mart: 3, conv: 20, park: 4, cafe: 40, culture: 5, bank: 8, pharmacy: 6,
    noxious: [], view: "블루", sunlight: "우수", noise: 55,
    layout: "4베이판상", parkingRatio: 1.55, floorAreaRatio: 299,
    energyGrade: 1, greenBldg: "최우수", quakeDesign: true, exclusiveRatio: 79.2, hasPool: true,
    discountPct: 0, loanFree: false, loanFreePct: 0, optionFree: false,
    optionValue: 0, balconyFree: false, balconyValue: 0, cashback: 0, contractDiscount: false,
    unsoldRate: 1.9, recentTrades6m: 85, supplyRatio: 35,
    builderCreditGrade: "AA", builderDebtRatio: 80, hugGuarantee: true,
    isRegulated: true, dsr40pass: true, popGrowth: 0.1,
    transitDev: "9호선(기존)", devDist: 0.3, cityDev: "반포 재건축 정비구역", industryDev: "",
    nearbyMedian: 145000, jeonseRate: 42, pir: 22, psr: 0.93, dataReliability: 98,
    heroColor: "#1E3A5F",
    benefits: [],
  },
  // ── 경기 ──
  {
    id: "g1", name: "화성 동탄 자이", dong: "동탄동", gu: "화성시", region: "경기",
    area: 84, price: 62000, pp: 2441, floors: "25~35층", maxFloor: 35,
    units: 2300, unsold: 120, builder: "GS건설", completion: "2026-06",
    subwayDist: 800, busRoutes: 15, icDist: 2.5, ktxDist: 5,
    schoolScore: 82, schoolGrade: "우수",
    hospital: 4, mart: 3, conv: 15, park: 3, cafe: 20, culture: 2, bank: 4, pharmacy: 3,
    noxious: [], view: "그린", sunlight: "우수", noise: 50,
    layout: "4베이판상", parkingRatio: 1.48, floorAreaRatio: 230,
    energyGrade: 1, greenBldg: "최우수", quakeDesign: true, exclusiveRatio: 78.1, hasPool: true,
    discountPct: 3, loanFree: true, loanFreePct: 50, optionFree: true,
    optionValue: 800, balconyFree: false, balconyValue: 0, cashback: 0, contractDiscount: false,
    unsoldRate: 5.2, recentTrades6m: 55, supplyRatio: 145,
    builderCreditGrade: "AA-", builderDebtRatio: 95, hugGuarantee: true,
    isRegulated: false, dsr40pass: true, popGrowth: 2.5,
    transitDev: "GTX-A(기존)", devDist: 1.0, cityDev: "동탄 신도시 3단계", industryDev: "삼성 반도체 클러스터",
    nearbyMedian: 58000, jeonseRate: 58, pir: 9.5, psr: 0.94, dataReliability: 92,
    heroColor: "#22C55E",
    benefits: ["분양가 3% 할인", "중도금 50% 무이자", "시스템에어컨 무상"],
  },
  // ── 부산 ──
  {
    id: "b1", name: "해운대 엘시티 더샵", dong: "우동", gu: "해운대구", region: "부산",
    area: 84, price: 72000, pp: 2835, floors: "30~50층", maxFloor: 50,
    units: 980, unsold: 35, builder: "포스코이앤씨", completion: "2026-08",
    subwayDist: 400, busRoutes: 20, icDist: 3, ktxDist: 25,
    schoolScore: 75, schoolGrade: "우수",
    hospital: 5, mart: 2, conv: 14, park: 3, cafe: 30, culture: 3, bank: 4, pharmacy: 3,
    noxious: [], view: "블루", sunlight: "우수", noise: 52,
    layout: "4베이타워", parkingRatio: 1.52, floorAreaRatio: 350,
    energyGrade: 1, greenBldg: "최우수", quakeDesign: true, exclusiveRatio: 77.5, hasPool: true,
    discountPct: 4, loanFree: true, loanFreePct: 60, optionFree: false,
    optionValue: 0, balconyFree: false, balconyValue: 0, cashback: 0, contractDiscount: true,
    unsoldRate: 3.6, recentTrades6m: 42, supplyRatio: 95,
    builderCreditGrade: "A+", builderDebtRatio: 135, hugGuarantee: true,
    isRegulated: false, dsr40pass: true, popGrowth: -0.3,
    transitDev: "부산2호선(기존)", devDist: 0.5, cityDev: "해운대 관광리조트", industryDev: "",
    nearbyMedian: 68000, jeonseRate: 48, pir: 12, psr: 0.95, dataReliability: 90,
    heroColor: "#0EA5E9",
    benefits: ["분양가 4% 할인", "중도금 60% 무이자"],
  },
  // ── 대전 ──
  {
    id: "d1", name: "유성 더샵 포레나", dong: "봉명동", gu: "유성구", region: "대전",
    area: 84, price: 42000, pp: 1653, floors: "15~25층", maxFloor: 25,
    units: 850, unsold: 47, builder: "포스코이앤씨", completion: "2026-03",
    subwayDist: 650, busRoutes: 12, icDist: 3.5, ktxDist: 8,
    schoolScore: 78, schoolGrade: "우수",
    hospital: 3, mart: 2, conv: 8, park: 2, cafe: 15, culture: 1, bank: 3, pharmacy: 2,
    noxious: [], view: "그린", sunlight: "양호", noise: 55,
    layout: "4베이판상", parkingRatio: 1.45, floorAreaRatio: 220,
    energyGrade: 2, greenBldg: "우수", quakeDesign: true, exclusiveRatio: 78.5, hasPool: false,
    discountPct: 5, loanFree: true, loanFreePct: 60, optionFree: true,
    optionValue: 750, balconyFree: false, balconyValue: 0, cashback: 0, contractDiscount: false,
    unsoldRate: 5.5, recentTrades6m: 28, supplyRatio: 124,
    builderCreditGrade: "A+", builderDebtRatio: 135, hugGuarantee: true,
    isRegulated: false, dsr40pass: true, popGrowth: 0.3,
    transitDev: "대전2호선(계획)", devDist: 1.2, cityDev: "봉명지구 주거타운", industryDev: "나노반도체단지",
    nearbyMedian: 37800, jeonseRate: 68, pir: 6.2, psr: 0.90, dataReliability: 85,
    heroColor: "#4A90D9",
    benefits: ["중도금 무이자", "시스템에어컨 무상", "분양가 5% 할인"],
  },
  {
    id: "d2", name: "둔산 푸르지오 시티", dong: "둔산동", gu: "서구", region: "대전",
    area: 84, price: 48000, pp: 1890, floors: "20~35층", maxFloor: 35,
    units: 1200, unsold: 23, builder: "대우건설", completion: "2026-06",
    subwayDist: 380, busRoutes: 22, icDist: 5, ktxDist: 12,
    schoolScore: 92, schoolGrade: "최우수",
    hospital: 5, mart: 3, conv: 12, park: 3, cafe: 25, culture: 3, bank: 5, pharmacy: 4,
    noxious: [], view: "천공", sunlight: "우수", noise: 60,
    layout: "4베이타워", parkingRatio: 1.52, floorAreaRatio: 280,
    energyGrade: 1, greenBldg: "최우수", quakeDesign: true, exclusiveRatio: 76.2, hasPool: true,
    discountPct: 3, loanFree: true, loanFreePct: 60, optionFree: false,
    optionValue: 0, balconyFree: false, balconyValue: 0, cashback: 0, contractDiscount: true,
    unsoldRate: 1.9, recentTrades6m: 45, supplyRatio: 80,
    builderCreditGrade: "AA-", builderDebtRatio: 110, hugGuarantee: true,
    isRegulated: false, dsr40pass: true, popGrowth: 0.5,
    transitDev: "없음", devDist: 99, cityDev: "둔산 리모델링추진", industryDev: "",
    nearbyMedian: 44200, jeonseRate: 62, pir: 7.1, psr: 0.92, dataReliability: 92,
    heroColor: "#6366F1",
    benefits: ["중도금 60% 무이자", "계약금 5% 할인"],
  },
  // ── 대구 ──
  {
    id: "dg1", name: "수성 힐스테이트", dong: "범어동", gu: "수성구", region: "대구",
    area: 84, price: 55000, pp: 2165, floors: "20~35층", maxFloor: 35,
    units: 750, unsold: 40, builder: "현대건설", completion: "2026-05",
    subwayDist: 350, busRoutes: 18, icDist: 5, ktxDist: 10,
    schoolScore: 88, schoolGrade: "우수",
    hospital: 4, mart: 2, conv: 11, park: 2, cafe: 18, culture: 2, bank: 4, pharmacy: 3,
    noxious: [], view: "그린", sunlight: "우수", noise: 52,
    layout: "4베이판상", parkingRatio: 1.50, floorAreaRatio: 240,
    energyGrade: 1, greenBldg: "우수", quakeDesign: true, exclusiveRatio: 79.0, hasPool: false,
    discountPct: 3, loanFree: true, loanFreePct: 50, optionFree: false,
    optionValue: 0, balconyFree: false, balconyValue: 0, cashback: 0, contractDiscount: false,
    unsoldRate: 5.3, recentTrades6m: 35, supplyRatio: 110,
    builderCreditGrade: "AA", builderDebtRatio: 85, hugGuarantee: true,
    isRegulated: false, dsr40pass: true, popGrowth: -0.5,
    transitDev: "대구4호선(계획)", devDist: 2.0, cityDev: "수성 메디컬지구", industryDev: "",
    nearbyMedian: 52000, jeonseRate: 55, pir: 8.5, psr: 0.95, dataReliability: 88,
    heroColor: "#EC4899",
    benefits: ["분양가 3% 할인", "중도금 50% 무이자"],
  },
  // ── 광주 ──
  {
    id: "gj1", name: "광주 첨단 e편한세상", dong: "월계동", gu: "광산구", region: "광주",
    area: 84, price: 35000, pp: 1378, floors: "15~25층", maxFloor: 25,
    units: 600, unsold: 80, builder: "DL이앤씨", completion: "2026-02",
    subwayDist: 500, busRoutes: 14, icDist: 3, ktxDist: 20,
    schoolScore: 70, schoolGrade: "보통",
    hospital: 3, mart: 2, conv: 8, park: 2, cafe: 10, culture: 1, bank: 2, pharmacy: 2,
    noxious: [], view: "그린", sunlight: "양호", noise: 48,
    layout: "4베이판상", parkingRatio: 1.40, floorAreaRatio: 210,
    energyGrade: 2, greenBldg: "우수", quakeDesign: true, exclusiveRatio: 77.8, hasPool: false,
    discountPct: 7, loanFree: true, loanFreePct: 80, optionFree: true,
    optionValue: 600, balconyFree: true, balconyValue: 1500, cashback: 0, contractDiscount: true,
    unsoldRate: 13.3, recentTrades6m: 15, supplyRatio: 140,
    builderCreditGrade: "A", builderDebtRatio: 165, hugGuarantee: true,
    isRegulated: false, dsr40pass: true, popGrowth: -0.4,
    transitDev: "광주2호선(계획)", devDist: 1.5, cityDev: "첨단과학산업단지", industryDev: "AI 스타트업 허브",
    nearbyMedian: 30000, jeonseRate: 72, pir: 5.0, psr: 0.84, dataReliability: 78,
    heroColor: "#F97316",
    benefits: ["분양가 7% 할인", "중도금 80% 무이자", "옵션 무상", "발코니 확장 무상"],
  },
  // ── 세종 ──
  {
    id: "sj1", name: "세종 국회의사당 근처 포레나", dong: "나성동", gu: "세종시", region: "세종",
    area: 84, price: 47000, pp: 1850, floors: "20~30층", maxFloor: 30,
    units: 1100, unsold: 55, builder: "한화건설", completion: "2026-04",
    subwayDist: 9999, busRoutes: 10, icDist: 2, ktxDist: 30,
    schoolScore: 80, schoolGrade: "우수",
    hospital: 2, mart: 2, conv: 6, park: 4, cafe: 8, culture: 1, bank: 2, pharmacy: 1,
    noxious: [], view: "그린", sunlight: "우수", noise: 42,
    layout: "4베이판상", parkingRatio: 1.60, floorAreaRatio: 190,
    energyGrade: 1, greenBldg: "최우수", quakeDesign: true, exclusiveRatio: 80.5, hasPool: false,
    discountPct: 4, loanFree: true, loanFreePct: 60, optionFree: false,
    optionValue: 0, balconyFree: false, balconyValue: 0, cashback: 0, contractDiscount: false,
    unsoldRate: 5.0, recentTrades6m: 30, supplyRatio: 160,
    builderCreditGrade: "A+", builderDebtRatio: 120, hugGuarantee: true,
    isRegulated: false, dsr40pass: true, popGrowth: 3.5,
    transitDev: "세종 BRT(기존)", devDist: 0.8, cityDev: "행정중심복합도시 5-2생활권", industryDev: "국회 이전 추진",
    nearbyMedian: 43000, jeonseRate: 60, pir: 6.8, psr: 0.91, dataReliability: 85,
    heroColor: "#8B5CF6",
    benefits: ["분양가 4% 할인", "중도금 60% 무이자"],
  },
  // ── 충남 천안 ──
  {
    id: "cn1", name: "천안 불당 아이파크", dong: "불당동", gu: "천안시", region: "충남",
    area: 84, price: 45000, pp: 1772, floors: "20~30층", maxFloor: 30,
    units: 900, unsold: 60, builder: "HDC현대산업개발", completion: "2026-07",
    subwayDist: 1200, busRoutes: 10, icDist: 2, ktxDist: 3,
    schoolScore: 75, schoolGrade: "우수",
    hospital: 3, mart: 2, conv: 9, park: 2, cafe: 12, culture: 1, bank: 3, pharmacy: 2,
    noxious: [], view: "천공", sunlight: "양호", noise: 55,
    layout: "4베이판상", parkingRatio: 1.42, floorAreaRatio: 225,
    energyGrade: 2, greenBldg: "우수", quakeDesign: true, exclusiveRatio: 78.0, hasPool: false,
    discountPct: 5, loanFree: true, loanFreePct: 70, optionFree: true,
    optionValue: 500, balconyFree: false, balconyValue: 0, cashback: 200, contractDiscount: true,
    unsoldRate: 6.7, recentTrades6m: 22, supplyRatio: 130,
    builderCreditGrade: "A+", builderDebtRatio: 140, hugGuarantee: true,
    isRegulated: false, dsr40pass: true, popGrowth: 0.8,
    transitDev: "수도권전철1호선(기존)", devDist: 1.0, cityDev: "불당 신도심 확장", industryDev: "삼성SDI·천안공장",
    nearbyMedian: 40000, jeonseRate: 65, pir: 6.0, psr: 0.89, dataReliability: 82,
    heroColor: "#14B8A6",
    benefits: ["분양가 5% 할인", "중도금 70% 무이자", "옵션 무상", "200만원 캐시백"],
  },
  // ── 경남 창원 ──
  {
    id: "gn1", name: "창원 중앙 푸르지오", dong: "중앙동", gu: "창원시", region: "경남",
    area: 84, price: 38000, pp: 1496, floors: "15~25층", maxFloor: 25,
    units: 700, unsold: 95, builder: "대우건설", completion: "2025-11",
    subwayDist: 9999, busRoutes: 16, icDist: 3, ktxDist: 8,
    schoolScore: 68, schoolGrade: "보통",
    hospital: 3, mart: 2, conv: 7, park: 1, cafe: 10, culture: 1, bank: 3, pharmacy: 2,
    noxious: ["철도인접"], view: "천공", sunlight: "양호", noise: 62,
    layout: "3베이판상", parkingRatio: 1.35, floorAreaRatio: 235,
    energyGrade: 2, greenBldg: "일반", quakeDesign: true, exclusiveRatio: 76.5, hasPool: false,
    discountPct: 8, loanFree: true, loanFreePct: 100, optionFree: true,
    optionValue: 500, balconyFree: true, balconyValue: 1600, cashback: 100, contractDiscount: true,
    unsoldRate: 13.6, recentTrades6m: 10, supplyRatio: 150,
    builderCreditGrade: "A", builderDebtRatio: 160, hugGuarantee: true,
    isRegulated: false, dsr40pass: true, popGrowth: -0.8,
    transitDev: "창원경전선(기존)", devDist: 0.5, cityDev: "창원 국가산업단지 리모델링", industryDev: "",
    nearbyMedian: 32000, jeonseRate: 74, pir: 5.2, psr: 0.84, dataReliability: 75,
    heroColor: "#EF4444",
    benefits: ["분양가 8% 할인", "중도금 전액 무이자", "옵션 무상", "발코니 확장 무상", "100만원 캐시백"],
  },
  // ── 강원 춘천 ──
  {
    id: "gw1", name: "춘천 후평 데시앙", dong: "후평동", gu: "춘천시", region: "강원",
    area: 84, price: 32000, pp: 1260, floors: "15~20층", maxFloor: 20,
    units: 450, unsold: 110, builder: "태영건설", completion: "2025-10",
    subwayDist: 2500, busRoutes: 8, icDist: 4, ktxDist: 2,
    schoolScore: 60, schoolGrade: "보통",
    hospital: 2, mart: 1, conv: 5, park: 3, cafe: 6, culture: 0, bank: 2, pharmacy: 1,
    noxious: [], view: "블루", sunlight: "양호", noise: 45,
    layout: "3베이판상", parkingRatio: 1.30, floorAreaRatio: 210,
    energyGrade: 2, greenBldg: "일반", quakeDesign: true, exclusiveRatio: 76.0, hasPool: false,
    discountPct: 10, loanFree: true, loanFreePct: 100, optionFree: true,
    optionValue: 400, balconyFree: true, balconyValue: 1200, cashback: 200, contractDiscount: true,
    unsoldRate: 24.4, recentTrades6m: 5, supplyRatio: 180,
    builderCreditGrade: "A-", builderDebtRatio: 180, hugGuarantee: true,
    isRegulated: false, dsr40pass: true, popGrowth: -1.2,
    transitDev: "경춘선 KTX(기존)", devDist: 1.5, cityDev: "레고랜드 관광특구", industryDev: "",
    nearbyMedian: 25000, jeonseRate: 78, pir: 4.5, psr: 0.78, dataReliability: 68,
    heroColor: "#06B6D4",
    benefits: ["분양가 10% 할인", "중도금 전액 무이자", "옵션 무상", "발코니 확장 무상", "200만원 캐시백"],
  },
  // ── 제주 ──
  {
    id: "jj1", name: "제주 노형 롯데캐슬", dong: "노형동", gu: "제주시", region: "제주",
    area: 84, price: 40000, pp: 1575, floors: "15~20층", maxFloor: 20,
    units: 350, unsold: 75, builder: "롯데건설", completion: "2026-01",
    subwayDist: 9999, busRoutes: 8, icDist: 5, ktxDist: 9999,
    schoolScore: 62, schoolGrade: "보통",
    hospital: 2, mart: 1, conv: 6, park: 2, cafe: 12, culture: 1, bank: 2, pharmacy: 1,
    noxious: [], view: "블루", sunlight: "우수", noise: 40,
    layout: "3베이타워", parkingRatio: 1.25, floorAreaRatio: 200,
    energyGrade: 2, greenBldg: "일반", quakeDesign: true, exclusiveRatio: 75.5, hasPool: false,
    discountPct: 6, loanFree: true, loanFreePct: 80, optionFree: true,
    optionValue: 500, balconyFree: true, balconyValue: 1300, cashback: 0, contractDiscount: true,
    unsoldRate: 21.4, recentTrades6m: 8, supplyRatio: 170,
    builderCreditGrade: "A", builderDebtRatio: 155, hugGuarantee: true,
    isRegulated: false, dsr40pass: true, popGrowth: -0.6,
    transitDev: "없음", devDist: 99, cityDev: "제2공항(추진)", industryDev: "",
    nearbyMedian: 35000, jeonseRate: 50, pir: 7.0, psr: 0.88, dataReliability: 72,
    heroColor: "#FB923C",
    benefits: ["분양가 6% 할인", "중도금 80% 무이자", "옵션 무상", "발코니 확장 무상"],
  },
];
