/* eslint-disable no-unused-vars */
// AUTO-GENERATED by `supabase gen types typescript --project-id rwdtljipvmqpazrimyns --schema public`
// 수동 편집 금지. 갱신 시 동일 명령 재실행 (M2b-1 절차)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      admin_settings: {
        Row: {
          key: string
          updated_at: string
          updated_by: string | null
          value: Json
        }
        Insert: {
          key: string
          updated_at: string
          updated_by?: string | null
          value: Json
        }
        Update: {
          key?: string
          updated_at?: string
          updated_by?: string | null
          value?: Json
        }
        Relationships: []
      }
      agent_verifications: {
        Row: {
          business_number: string | null
          business_verified: boolean
          id: number
          license_doc_path: string | null
          license_number: string | null
          license_verified: boolean
          office_name: string | null
          rejection_reason: string | null
          representative_name: string
          reviewed_at: string | null
          reviewed_by: string | null
          submitted_at: string
          updated_at: string
          user_id: string
          verification_status: string
        }
        Insert: {
          business_number?: string | null
          business_verified?: boolean
          id?: number
          license_doc_path?: string | null
          license_number?: string | null
          license_verified?: boolean
          office_name?: string | null
          rejection_reason?: string | null
          representative_name: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          submitted_at?: string
          updated_at?: string
          user_id: string
          verification_status?: string
        }
        Update: {
          business_number?: string | null
          business_verified?: boolean
          id?: number
          license_doc_path?: string | null
          license_number?: string | null
          license_verified?: boolean
          office_name?: string | null
          rejection_reason?: string | null
          representative_name?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          submitted_at?: string
          updated_at?: string
          user_id?: string
          verification_status?: string
        }
        Relationships: [
          {
            foreignKeyName: "agent_verifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "user_profiles"
            referencedColumns: ["user_id"]
          },
        ]
      }
      air_quality_stations: {
        Row: {
          address: string | null
          lat: number | null
          lng: number | null
          station_name: string
          updated_at: string | null
        }
        Insert: {
          address?: string | null
          lat?: number | null
          lng?: number | null
          station_name: string
          updated_at?: string | null
        }
        Update: {
          address?: string | null
          lat?: number | null
          lng?: number | null
          station_name?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      apartments: {
        Row: {
          address: string | null
          air_quality: Json | null
          announcement_url: string | null
          avg_maintenance_cost: number | null
          balcony_free: boolean | null
          balcony_value: number | null
          benefits: Json | null
          bjd_code: string | null
          builder: string | null
          building_coverage_ratio: number | null
          cashback: number | null
          cats_cache: Json | null
          city_dev: string | null
          competition_applicants: number | null
          competition_rate: number | null
          competition_supply: number | null
          completion: string | null
          contract_discount: boolean | null
          corridor_type: string | null
          created_at: string | null
          crime_safety_grade: number | null
          dev_dist: number | null
          discount_pct: number | null
          district: string | null
          dong: string | null
          dsr40pass: boolean | null
          elec_usage_kwh: number | null
          energy_collected_at: string | null
          energy_grade: number | null
          exclusive_ratio: number | null
          floor_area_ratio: number | null
          floors: string | null
          gas_usage_mj: number | null
          green_bldg: string | null
          gu: string | null
          has_pool: boolean | null
          heat_fuel: string | null
          heating: string | null
          id: string
          industry_dev: string | null
          is_regulated: boolean | null
          lat: number | null
          layout: string | null
          lng: number | null
          loan_free: boolean | null
          loan_free_pct: number | null
          lot_main: number | null
          lot_sub: number | null
          max_floor: number | null
          name: string
          naver_avg_floor: number | null
          naver_build_year: number | null
          naver_fetched_at: string | null
          naver_jeonse_count: number | null
          naver_jeonse_rate: number | null
          naver_nearby_avg: number | null
          naver_nearby_count: number | null
          naver_nearby_median: number | null
          naver_presale_no: string | null
          naver_presale_seq: string | null
          naver_school_walk_min: number | null
          naver_sell_count: number | null
          naver_wolse_count: number | null
          noise: number | null
          noxious: Json | null
          noxious_dist: number | null
          option_free: boolean | null
          option_value: number | null
          parking_ratio: number | null
          presale_buildings: number | null
          presale_features: string | null
          presale_fetched_at: string | null
          presale_general_supply: number | null
          presale_housing_type: string | null
          presale_image_url: string | null
          presale_inquiry: string | null
          presale_max_price: number | null
          presale_min_price: number | null
          presale_move_in: string | null
          presale_parking: number | null
          presale_pp: number | null
          presale_recruit_date: string | null
          presale_schedule: Json | null
          presale_stage: string | null
          presale_stage_code: string | null
          presale_type: string | null
          primary_direction: string | null
          quake_design: boolean | null
          region: string
          road_address: string | null
          scores_computed_at: string | null
          sunlight: string | null
          transit_dev: string | null
          unit_source: string | null
          units: number | null
          unsold: number | null
          unsold_rate: number | null
          updated_at: string | null
          view: string | null
        }
        Insert: {
          address?: string | null
          air_quality?: Json | null
          announcement_url?: string | null
          avg_maintenance_cost?: number | null
          balcony_free?: boolean | null
          balcony_value?: number | null
          benefits?: Json | null
          bjd_code?: string | null
          builder?: string | null
          building_coverage_ratio?: number | null
          cashback?: number | null
          cats_cache?: Json | null
          city_dev?: string | null
          competition_applicants?: number | null
          competition_rate?: number | null
          competition_supply?: number | null
          completion?: string | null
          contract_discount?: boolean | null
          corridor_type?: string | null
          created_at?: string | null
          crime_safety_grade?: number | null
          dev_dist?: number | null
          discount_pct?: number | null
          district?: string | null
          dong?: string | null
          dsr40pass?: boolean | null
          elec_usage_kwh?: number | null
          energy_collected_at?: string | null
          energy_grade?: number | null
          exclusive_ratio?: number | null
          floor_area_ratio?: number | null
          floors?: string | null
          gas_usage_mj?: number | null
          green_bldg?: string | null
          gu?: string | null
          has_pool?: boolean | null
          heat_fuel?: string | null
          heating?: string | null
          id: string
          industry_dev?: string | null
          is_regulated?: boolean | null
          lat?: number | null
          layout?: string | null
          lng?: number | null
          loan_free?: boolean | null
          loan_free_pct?: number | null
          lot_main?: number | null
          lot_sub?: number | null
          max_floor?: number | null
          name: string
          naver_avg_floor?: number | null
          naver_build_year?: number | null
          naver_fetched_at?: string | null
          naver_jeonse_count?: number | null
          naver_jeonse_rate?: number | null
          naver_nearby_avg?: number | null
          naver_nearby_count?: number | null
          naver_nearby_median?: number | null
          naver_presale_no?: string | null
          naver_presale_seq?: string | null
          naver_school_walk_min?: number | null
          naver_sell_count?: number | null
          naver_wolse_count?: number | null
          noise?: number | null
          noxious?: Json | null
          noxious_dist?: number | null
          option_free?: boolean | null
          option_value?: number | null
          parking_ratio?: number | null
          presale_buildings?: number | null
          presale_features?: string | null
          presale_fetched_at?: string | null
          presale_general_supply?: number | null
          presale_housing_type?: string | null
          presale_image_url?: string | null
          presale_inquiry?: string | null
          presale_max_price?: number | null
          presale_min_price?: number | null
          presale_move_in?: string | null
          presale_parking?: number | null
          presale_pp?: number | null
          presale_recruit_date?: string | null
          presale_schedule?: Json | null
          presale_stage?: string | null
          presale_stage_code?: string | null
          presale_type?: string | null
          primary_direction?: string | null
          quake_design?: boolean | null
          region: string
          road_address?: string | null
          scores_computed_at?: string | null
          sunlight?: string | null
          transit_dev?: string | null
          unit_source?: string | null
          units?: number | null
          unsold?: number | null
          unsold_rate?: number | null
          updated_at?: string | null
          view?: string | null
        }
        Update: {
          address?: string | null
          air_quality?: Json | null
          announcement_url?: string | null
          avg_maintenance_cost?: number | null
          balcony_free?: boolean | null
          balcony_value?: number | null
          benefits?: Json | null
          bjd_code?: string | null
          builder?: string | null
          building_coverage_ratio?: number | null
          cashback?: number | null
          cats_cache?: Json | null
          city_dev?: string | null
          competition_applicants?: number | null
          competition_rate?: number | null
          competition_supply?: number | null
          completion?: string | null
          contract_discount?: boolean | null
          corridor_type?: string | null
          created_at?: string | null
          crime_safety_grade?: number | null
          dev_dist?: number | null
          discount_pct?: number | null
          district?: string | null
          dong?: string | null
          dsr40pass?: boolean | null
          elec_usage_kwh?: number | null
          energy_collected_at?: string | null
          energy_grade?: number | null
          exclusive_ratio?: number | null
          floor_area_ratio?: number | null
          floors?: string | null
          gas_usage_mj?: number | null
          green_bldg?: string | null
          gu?: string | null
          has_pool?: boolean | null
          heat_fuel?: string | null
          heating?: string | null
          id?: string
          industry_dev?: string | null
          is_regulated?: boolean | null
          lat?: number | null
          layout?: string | null
          lng?: number | null
          loan_free?: boolean | null
          loan_free_pct?: number | null
          lot_main?: number | null
          lot_sub?: number | null
          max_floor?: number | null
          name?: string
          naver_avg_floor?: number | null
          naver_build_year?: number | null
          naver_fetched_at?: string | null
          naver_jeonse_count?: number | null
          naver_jeonse_rate?: number | null
          naver_nearby_avg?: number | null
          naver_nearby_count?: number | null
          naver_nearby_median?: number | null
          naver_presale_no?: string | null
          naver_presale_seq?: string | null
          naver_school_walk_min?: number | null
          naver_sell_count?: number | null
          naver_wolse_count?: number | null
          noise?: number | null
          noxious?: Json | null
          noxious_dist?: number | null
          option_free?: boolean | null
          option_value?: number | null
          parking_ratio?: number | null
          presale_buildings?: number | null
          presale_features?: string | null
          presale_fetched_at?: string | null
          presale_general_supply?: number | null
          presale_housing_type?: string | null
          presale_image_url?: string | null
          presale_inquiry?: string | null
          presale_max_price?: number | null
          presale_min_price?: number | null
          presale_move_in?: string | null
          presale_parking?: number | null
          presale_pp?: number | null
          presale_recruit_date?: string | null
          presale_schedule?: Json | null
          presale_stage?: string | null
          presale_stage_code?: string | null
          presale_type?: string | null
          primary_direction?: string | null
          quake_design?: boolean | null
          region?: string
          road_address?: string | null
          scores_computed_at?: string | null
          sunlight?: string | null
          transit_dev?: string | null
          unit_source?: string | null
          units?: number | null
          unsold?: number | null
          unsold_rate?: number | null
          updated_at?: string | null
          view?: string | null
        }
        Relationships: []
      }
      api_quota_log: {
        Row: {
          api_name: string
          call_count: number
          collector: string
          id: number
          log_date: string
          recorded_at: string
        }
        Insert: {
          api_name: string
          call_count: number
          collector: string
          id?: number
          log_date?: string
          recorded_at?: string
        }
        Update: {
          api_name?: string
          call_count?: number
          collector?: string
          id?: number
          log_date?: string
          recorded_at?: string
        }
        Relationships: []
      }
      applyhome_events: {
        Row: {
          apartment_id: string
          applicants: number
          created_at: string | null
          house_manage_no: string
          id: number
          rate: number | null
          recorded_at: string
          supply: number
        }
        Insert: {
          apartment_id: string
          applicants: number
          created_at?: string | null
          house_manage_no: string
          id?: number
          rate?: number | null
          recorded_at?: string
          supply: number
        }
        Update: {
          apartment_id?: string
          applicants?: number
          created_at?: string | null
          house_manage_no?: string
          id?: number
          rate?: number | null
          recorded_at?: string
          supply?: number
        }
        Relationships: [
          {
            foreignKeyName: "applyhome_events_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: false
            referencedRelation: "apartments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applyhome_events_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: false
            referencedRelation: "apartments_flat"
            referencedColumns: ["id"]
          },
        ]
      }
      article_price_history: {
        Row: {
          article_no: string
          id: number
          price: number | null
          recorded_at: string
          rent_price: number | null
        }
        Insert: {
          article_no: string
          id?: number
          price?: number | null
          recorded_at: string
          rent_price?: number | null
        }
        Update: {
          article_no?: string
          id?: number
          price?: number | null
          recorded_at?: string
          rent_price?: number | null
        }
        Relationships: []
      }
      articles: {
        Row: {
          acquisition_tax: string | null
          area1_m2: number | null
          area2_m2: number | null
          article_confirm_ymd: string | null
          article_feature_desc: string | null
          article_name: string | null
          article_no: string
          article_real_estate_type_name: string | null
          bathroom_count: number | null
          broker_fee: string | null
          building_name: string | null
          complex_name: string | null
          complex_no: string
          created_at: string
          deal_or_warrant_prc: string | null
          detail_crawled: boolean
          detail_description: string | null
          direction: string | null
          first_seen_at: string
          floor_info: string | null
          floor_number: number | null
          heating_type: string | null
          is_active: boolean
          is_presale: boolean
          is_verified: boolean
          jibun_address: string | null
          last_seen_at: string
          latitude: number | null
          longitude: number | null
          maintenance_cost: string | null
          move_in_date: string | null
          numeric_maintenance_cost: number | null
          numeric_price: number | null
          numeric_rent_price: number | null
          parking_count: string | null
          photo_urls: string[] | null
          previous_price: number | null
          price_changed_at: string | null
          price_per_pyeong: number | null
          realtor_address: string | null
          realtor_id: string | null
          realtor_name: string | null
          realtor_phone: string | null
          realtor_phone_display: string | null
          rent_prc: string | null
          representative_img_url: string | null
          room_count: number | null
          tags: string[] | null
          total_floor_count: number | null
          trade_type_name: string | null
          updated_at: string
          use_approve_ymd: string | null
        }
        Insert: {
          acquisition_tax?: string | null
          area1_m2?: number | null
          area2_m2?: number | null
          article_confirm_ymd?: string | null
          article_feature_desc?: string | null
          article_name?: string | null
          article_no: string
          article_real_estate_type_name?: string | null
          bathroom_count?: number | null
          broker_fee?: string | null
          building_name?: string | null
          complex_name?: string | null
          complex_no: string
          created_at?: string
          deal_or_warrant_prc?: string | null
          detail_crawled?: boolean
          detail_description?: string | null
          direction?: string | null
          first_seen_at?: string
          floor_info?: string | null
          floor_number?: number | null
          heating_type?: string | null
          is_active?: boolean
          is_presale?: boolean
          is_verified?: boolean
          jibun_address?: string | null
          last_seen_at?: string
          latitude?: number | null
          longitude?: number | null
          maintenance_cost?: string | null
          move_in_date?: string | null
          numeric_maintenance_cost?: number | null
          numeric_price?: number | null
          numeric_rent_price?: number | null
          parking_count?: string | null
          photo_urls?: string[] | null
          previous_price?: number | null
          price_changed_at?: string | null
          price_per_pyeong?: number | null
          realtor_address?: string | null
          realtor_id?: string | null
          realtor_name?: string | null
          realtor_phone?: string | null
          realtor_phone_display?: string | null
          rent_prc?: string | null
          representative_img_url?: string | null
          room_count?: number | null
          tags?: string[] | null
          total_floor_count?: number | null
          trade_type_name?: string | null
          updated_at?: string
          use_approve_ymd?: string | null
        }
        Update: {
          acquisition_tax?: string | null
          area1_m2?: number | null
          area2_m2?: number | null
          article_confirm_ymd?: string | null
          article_feature_desc?: string | null
          article_name?: string | null
          article_no?: string
          article_real_estate_type_name?: string | null
          bathroom_count?: number | null
          broker_fee?: string | null
          building_name?: string | null
          complex_name?: string | null
          complex_no?: string
          created_at?: string
          deal_or_warrant_prc?: string | null
          detail_crawled?: boolean
          detail_description?: string | null
          direction?: string | null
          first_seen_at?: string
          floor_info?: string | null
          floor_number?: number | null
          heating_type?: string | null
          is_active?: boolean
          is_presale?: boolean
          is_verified?: boolean
          jibun_address?: string | null
          last_seen_at?: string
          latitude?: number | null
          longitude?: number | null
          maintenance_cost?: string | null
          move_in_date?: string | null
          numeric_maintenance_cost?: number | null
          numeric_price?: number | null
          numeric_rent_price?: number | null
          parking_count?: string | null
          photo_urls?: string[] | null
          previous_price?: number | null
          price_changed_at?: string | null
          price_per_pyeong?: number | null
          realtor_address?: string | null
          realtor_id?: string | null
          realtor_name?: string | null
          realtor_phone?: string | null
          realtor_phone_display?: string | null
          rent_prc?: string | null
          representative_img_url?: string | null
          room_count?: number | null
          tags?: string[] | null
          total_floor_count?: number | null
          trade_type_name?: string | null
          updated_at?: string
          use_approve_ymd?: string | null
        }
        Relationships: []
      }
      audit_logs: {
        Row: {
          action: string
          created_at: string
          details: Json | null
          id: number
          ip_address: string | null
          target_id: string | null
          target_type: string | null
          user_id: string | null
        }
        Insert: {
          action: string
          created_at: string
          details?: Json | null
          id?: number
          ip_address?: string | null
          target_id?: string | null
          target_type?: string | null
          user_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string
          details?: Json | null
          id?: number
          ip_address?: string | null
          target_id?: string | null
          target_type?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      builders: {
        Row: {
          corp_code: string | null
          credit_grade: string | null
          debt_ratio: number | null
          hug_guarantee: boolean | null
          name: string
          updated_at: string | null
        }
        Insert: {
          corp_code?: string | null
          credit_grade?: string | null
          debt_ratio?: number | null
          hug_guarantee?: boolean | null
          name: string
          updated_at?: string | null
        }
        Update: {
          corp_code?: string | null
          credit_grade?: string | null
          debt_ratio?: number | null
          hug_guarantee?: boolean | null
          name?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      complex_price_history: {
        Row: {
          area_no: string | null
          base_month: string
          complex_no: string
          id: number
          price_avg: number | null
          price_lower: number | null
          price_upper: number | null
          recorded_at: string
          trade_type: string
        }
        Insert: {
          area_no?: string | null
          base_month: string
          complex_no: string
          id?: number
          price_avg?: number | null
          price_lower?: number | null
          price_upper?: number | null
          recorded_at?: string
          trade_type: string
        }
        Update: {
          area_no?: string | null
          base_month?: string
          complex_no?: string
          id?: number
          price_avg?: number | null
          price_lower?: number | null
          price_upper?: number | null
          recorded_at?: string
          trade_type?: string
        }
        Relationships: []
      }
      complex_pyeong_details: {
        Row: {
          avg_maintenance_cost: number | null
          bathroom_count: number | null
          complex_no: string
          created_at: string
          entrance_type: string | null
          exclusive_area: string | null
          exclusive_pyeong: string | null
          exclusive_rate: string | null
          floor_plan_url: string | null
          household_count_by_pyeong: string | null
          id: number
          latest_maintenance_cost: number | null
          maintenance_cost_basis: string | null
          pyeong_name: string | null
          pyeong_no: number
          room_count: number | null
          summer_maintenance_cost: number | null
          supply_area: string | null
          supply_area_double: number | null
          supply_pyeong: string | null
          updated_at: string
          winter_maintenance_cost: number | null
        }
        Insert: {
          avg_maintenance_cost?: number | null
          bathroom_count?: number | null
          complex_no: string
          created_at: string
          entrance_type?: string | null
          exclusive_area?: string | null
          exclusive_pyeong?: string | null
          exclusive_rate?: string | null
          floor_plan_url?: string | null
          household_count_by_pyeong?: string | null
          id?: number
          latest_maintenance_cost?: number | null
          maintenance_cost_basis?: string | null
          pyeong_name?: string | null
          pyeong_no: number
          room_count?: number | null
          summer_maintenance_cost?: number | null
          supply_area?: string | null
          supply_area_double?: number | null
          supply_pyeong?: string | null
          updated_at: string
          winter_maintenance_cost?: number | null
        }
        Update: {
          avg_maintenance_cost?: number | null
          bathroom_count?: number | null
          complex_no?: string
          created_at?: string
          entrance_type?: string | null
          exclusive_area?: string | null
          exclusive_pyeong?: string | null
          exclusive_rate?: string | null
          floor_plan_url?: string | null
          household_count_by_pyeong?: string | null
          id?: number
          latest_maintenance_cost?: number | null
          maintenance_cost_basis?: string | null
          pyeong_name?: string | null
          pyeong_no?: number
          room_count?: number | null
          summer_maintenance_cost?: number | null
          supply_area?: string | null
          supply_area_double?: number | null
          supply_pyeong?: string | null
          updated_at?: string
          winter_maintenance_cost?: number | null
        }
        Relationships: []
      }
      complexes: {
        Row: {
          address: string | null
          building_coverage_ratio: string | null
          complex_name: string
          complex_no: string
          construction_company: string | null
          corridor_type: string | null
          cortar_address: string | null
          cortar_no: string | null
          created_at: string
          detail_crawled_at: string | null
          dong: string | null
          earthquake_design: boolean | null
          entrance_type: string | null
          floor_area_ratio: string | null
          has_pool: boolean | null
          heat_fuel: string | null
          heat_fuel_type: string | null
          heat_method: string | null
          heat_method_type: string | null
          high_floor: number | null
          jeonse_rate: number | null
          last_crawled_at: string | null
          latitude: number | null
          longitude: number | null
          low_floor: number | null
          management_office_tel: string | null
          max_supply_area_m2: number | null
          min_supply_area_m2: number | null
          nearby_median_price: number | null
          parking_count_by_household: number | null
          real_estate_type_code: string | null
          real_estate_type_name: string | null
          recent_trades_6m: number | null
          road_address: string | null
          sido: string | null
          sigungu: string | null
          total_dong_count: number | null
          total_household_count: number | null
          total_parking_count: number | null
          updated_at: string
          use_approve_ymd: string | null
        }
        Insert: {
          address?: string | null
          building_coverage_ratio?: string | null
          complex_name: string
          complex_no: string
          construction_company?: string | null
          corridor_type?: string | null
          cortar_address?: string | null
          cortar_no?: string | null
          created_at?: string
          detail_crawled_at?: string | null
          dong?: string | null
          earthquake_design?: boolean | null
          entrance_type?: string | null
          floor_area_ratio?: string | null
          has_pool?: boolean | null
          heat_fuel?: string | null
          heat_fuel_type?: string | null
          heat_method?: string | null
          heat_method_type?: string | null
          high_floor?: number | null
          jeonse_rate?: number | null
          last_crawled_at?: string | null
          latitude?: number | null
          longitude?: number | null
          low_floor?: number | null
          management_office_tel?: string | null
          max_supply_area_m2?: number | null
          min_supply_area_m2?: number | null
          nearby_median_price?: number | null
          parking_count_by_household?: number | null
          real_estate_type_code?: string | null
          real_estate_type_name?: string | null
          recent_trades_6m?: number | null
          road_address?: string | null
          sido?: string | null
          sigungu?: string | null
          total_dong_count?: number | null
          total_household_count?: number | null
          total_parking_count?: number | null
          updated_at?: string
          use_approve_ymd?: string | null
        }
        Update: {
          address?: string | null
          building_coverage_ratio?: string | null
          complex_name?: string
          complex_no?: string
          construction_company?: string | null
          corridor_type?: string | null
          cortar_address?: string | null
          cortar_no?: string | null
          created_at?: string
          detail_crawled_at?: string | null
          dong?: string | null
          earthquake_design?: boolean | null
          entrance_type?: string | null
          floor_area_ratio?: string | null
          has_pool?: boolean | null
          heat_fuel?: string | null
          heat_fuel_type?: string | null
          heat_method?: string | null
          heat_method_type?: string | null
          high_floor?: number | null
          jeonse_rate?: number | null
          last_crawled_at?: string | null
          latitude?: number | null
          longitude?: number | null
          low_floor?: number | null
          management_office_tel?: string | null
          max_supply_area_m2?: number | null
          min_supply_area_m2?: number | null
          nearby_median_price?: number | null
          parking_count_by_household?: number | null
          real_estate_type_code?: string | null
          real_estate_type_name?: string | null
          recent_trades_6m?: number | null
          road_address?: string | null
          sido?: string | null
          sigungu?: string | null
          total_dong_count?: number | null
          total_household_count?: number | null
          total_parking_count?: number | null
          updated_at?: string
          use_approve_ymd?: string | null
        }
        Relationships: []
      }
      consults: {
        Row: {
          budget_max: number | null
          budget_min: number | null
          consult_type: string | null
          id: number
          interested_apts: string[] | null
          message: string | null
          name: string
          phone: string
          status: string | null
          submitted_at: string | null
        }
        Insert: {
          budget_max?: number | null
          budget_min?: number | null
          consult_type?: string | null
          id?: number
          interested_apts?: string[] | null
          message?: string | null
          name: string
          phone: string
          status?: string | null
          submitted_at?: string | null
        }
        Update: {
          budget_max?: number | null
          budget_min?: number | null
          consult_type?: string | null
          id?: number
          interested_apts?: string[] | null
          message?: string | null
          name?: string
          phone?: string
          status?: string | null
          submitted_at?: string | null
        }
        Relationships: []
      }
      crawl_jobs: {
        Row: {
          completed_at: string | null
          created_at: string
          error_message: string | null
          id: number
          job_type: string
          processed_items: number
          scheduler_job_id: string | null
          started_at: string | null
          status: string
          target_id: string | null
          total_items: number
        }
        Insert: {
          completed_at?: string | null
          created_at: string
          error_message?: string | null
          id?: number
          job_type: string
          processed_items: number
          scheduler_job_id?: string | null
          started_at?: string | null
          status: string
          target_id?: string | null
          total_items: number
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          error_message?: string | null
          id?: number
          job_type?: string
          processed_items?: number
          scheduler_job_id?: string | null
          started_at?: string | null
          status?: string
          target_id?: string | null
          total_items?: number
        }
        Relationships: []
      }
      crawler_checkpoints: {
        Row: {
          job_id: number
          state_json: Json
          updated_at: string
        }
        Insert: {
          job_id?: number
          state_json: Json
          updated_at: string
        }
        Update: {
          job_id?: number
          state_json?: Json
          updated_at?: string
        }
        Relationships: []
      }
      infra: {
        Row: {
          air_grade: string | null
          air_o3: number | null
          air_pm10: number | null
          air_pm25: number | null
          air_station_dist: number | null
          air_station_name: string | null
          air_updated_at: string | null
          apartment_id: string
          bank: number | null
          bank_dist: number | null
          cafe: number | null
          cafe_dist: number | null
          childcare: number | null
          childcare_count: number | null
          childcare_dist: number | null
          childcare_nearest_capacity: number | null
          childcare_nearest_dist: number | null
          childcare_nearest_name: string | null
          childcare_nearest_teachers: number | null
          childcare_nearest_type: string | null
          conv: number | null
          conv_dist: number | null
          crime_grade: string | null
          crime_score: number | null
          crime_updated_at: string | null
          culture: number | null
          culture_dist: number | null
          emergency: number | null
          emergency_beds: number | null
          emergency_dist: number | null
          emergency_hospital: number | null
          emergency_hospital_dist: number | null
          emergency_level: string | null
          hospital: number | null
          hospital_dist: number | null
          mart: number | null
          mart_dist: number | null
          nearby_facilities: Json | null
          park: number | null
          park_dist: number | null
          pharmacy: number | null
          pharmacy_dist: number | null
          police: number | null
          police_dist: number | null
          subway_dist: number | null
          updated_at: string | null
        }
        Insert: {
          air_grade?: string | null
          air_o3?: number | null
          air_pm10?: number | null
          air_pm25?: number | null
          air_station_dist?: number | null
          air_station_name?: string | null
          air_updated_at?: string | null
          apartment_id: string
          bank?: number | null
          bank_dist?: number | null
          cafe?: number | null
          cafe_dist?: number | null
          childcare?: number | null
          childcare_count?: number | null
          childcare_dist?: number | null
          childcare_nearest_capacity?: number | null
          childcare_nearest_dist?: number | null
          childcare_nearest_name?: string | null
          childcare_nearest_teachers?: number | null
          childcare_nearest_type?: string | null
          conv?: number | null
          conv_dist?: number | null
          crime_grade?: string | null
          crime_score?: number | null
          crime_updated_at?: string | null
          culture?: number | null
          culture_dist?: number | null
          emergency?: number | null
          emergency_beds?: number | null
          emergency_dist?: number | null
          emergency_hospital?: number | null
          emergency_hospital_dist?: number | null
          emergency_level?: string | null
          hospital?: number | null
          hospital_dist?: number | null
          mart?: number | null
          mart_dist?: number | null
          nearby_facilities?: Json | null
          park?: number | null
          park_dist?: number | null
          pharmacy?: number | null
          pharmacy_dist?: number | null
          police?: number | null
          police_dist?: number | null
          subway_dist?: number | null
          updated_at?: string | null
        }
        Update: {
          air_grade?: string | null
          air_o3?: number | null
          air_pm10?: number | null
          air_pm25?: number | null
          air_station_dist?: number | null
          air_station_name?: string | null
          air_updated_at?: string | null
          apartment_id?: string
          bank?: number | null
          bank_dist?: number | null
          cafe?: number | null
          cafe_dist?: number | null
          childcare?: number | null
          childcare_count?: number | null
          childcare_dist?: number | null
          childcare_nearest_capacity?: number | null
          childcare_nearest_dist?: number | null
          childcare_nearest_name?: string | null
          childcare_nearest_teachers?: number | null
          childcare_nearest_type?: string | null
          conv?: number | null
          conv_dist?: number | null
          crime_grade?: string | null
          crime_score?: number | null
          crime_updated_at?: string | null
          culture?: number | null
          culture_dist?: number | null
          emergency?: number | null
          emergency_beds?: number | null
          emergency_dist?: number | null
          emergency_hospital?: number | null
          emergency_hospital_dist?: number | null
          emergency_level?: string | null
          hospital?: number | null
          hospital_dist?: number | null
          mart?: number | null
          mart_dist?: number | null
          nearby_facilities?: Json | null
          park?: number | null
          park_dist?: number | null
          pharmacy?: number | null
          pharmacy_dist?: number | null
          police?: number | null
          police_dist?: number | null
          subway_dist?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "infra_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: true
            referencedRelation: "apartments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "infra_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: true
            referencedRelation: "apartments_flat"
            referencedColumns: ["id"]
          },
        ]
      }
      market_stats_history: {
        Row: {
          avg_price_sqm: number | null
          base_month: string
          gu: string
          id: number
          initial_sale_rate: number | null
          land_cost_ratio: number | null
          new_supply: number | null
          price_index: number | null
          recorded_at: string
          region: string
        }
        Insert: {
          avg_price_sqm?: number | null
          base_month: string
          gu?: string
          id?: number
          initial_sale_rate?: number | null
          land_cost_ratio?: number | null
          new_supply?: number | null
          price_index?: number | null
          recorded_at?: string
          region: string
        }
        Update: {
          avg_price_sqm?: number | null
          base_month?: string
          gu?: string
          id?: number
          initial_sale_rate?: number | null
          land_cost_ratio?: number | null
          new_supply?: number | null
          price_index?: number | null
          recorded_at?: string
          region?: string
        }
        Relationships: []
      }
      naver_api_call_counts: {
        Row: {
          bucket_hour: string
          call_count: number
          id: number
          label: string
        }
        Insert: {
          bucket_hour: string
          call_count?: number
          id?: number
          label: string
        }
        Update: {
          bucket_hour?: string
          call_count?: number
          id?: number
          label?: string
        }
        Relationships: []
      }
      prices: {
        Row: {
          apartment_id: string
          area: number | null
          house_type: string | null
          id: number
          pp: number | null
          price: number | null
          recorded_at: string
          supply_area: number | null
          supply_count: number | null
        }
        Insert: {
          apartment_id: string
          area?: number | null
          house_type?: string | null
          id?: number
          pp?: number | null
          price?: number | null
          recorded_at?: string
          supply_area?: number | null
          supply_count?: number | null
        }
        Update: {
          apartment_id?: string
          area?: number | null
          house_type?: string | null
          id?: number
          pp?: number | null
          price?: number | null
          recorded_at?: string
          supply_area?: number | null
          supply_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "prices_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: false
            referencedRelation: "apartments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "prices_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: false
            referencedRelation: "apartments_flat"
            referencedColumns: ["id"]
          },
        ]
      }
      rate_limit_counters: {
        Row: {
          count: number
          expires_at: string
          key: string
        }
        Insert: {
          count: number
          expires_at: string
          key: string
        }
        Update: {
          count?: number
          expires_at?: string
          key?: string
        }
        Relationships: []
      }
      regions: {
        Row: {
          avg_income: number | null
          avg_price: number | null
          avg_price_sqm: number | null
          gu: string | null
          households: number | null
          id: number
          initial_sale_rate: number | null
          jeonse_rate: number | null
          land_cost_ratio: number | null
          net_migration: number | null
          new_supply: number | null
          pop_growth: number | null
          population: number | null
          price_index: number | null
          recorded_at: string
          region: string
          regional_unsold: number | null
          supply_ratio: number | null
        }
        Insert: {
          avg_income?: number | null
          avg_price?: number | null
          avg_price_sqm?: number | null
          gu?: string | null
          households?: number | null
          id?: number
          initial_sale_rate?: number | null
          jeonse_rate?: number | null
          land_cost_ratio?: number | null
          net_migration?: number | null
          new_supply?: number | null
          pop_growth?: number | null
          population?: number | null
          price_index?: number | null
          recorded_at?: string
          region: string
          regional_unsold?: number | null
          supply_ratio?: number | null
        }
        Update: {
          avg_income?: number | null
          avg_price?: number | null
          avg_price_sqm?: number | null
          gu?: string | null
          households?: number | null
          id?: number
          initial_sale_rate?: number | null
          jeonse_rate?: number | null
          land_cost_ratio?: number | null
          net_migration?: number | null
          new_supply?: number | null
          pop_growth?: number | null
          population?: number | null
          price_index?: number | null
          recorded_at?: string
          region?: string
          regional_unsold?: number | null
          supply_ratio?: number | null
        }
        Relationships: []
      }
      schools: {
        Row: {
          apartment_id: string
          nearby_schools: Json | null
          school_grade: string | null
          school_score: number | null
          updated_at: string | null
        }
        Insert: {
          apartment_id: string
          nearby_schools?: Json | null
          school_grade?: string | null
          school_score?: number | null
          updated_at?: string | null
        }
        Update: {
          apartment_id?: string
          nearby_schools?: Json | null
          school_grade?: string | null
          school_score?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "schools_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: true
            referencedRelation: "apartments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "schools_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: true
            referencedRelation: "apartments_flat"
            referencedColumns: ["id"]
          },
        ]
      }
      subscribers: {
        Row: {
          apartment_id: string | null
          consent_at: string
          consent_source: string
          created_at: string
          gu: string | null
          id: number
          last_notified_at: string | null
          notify_count: number
          opt_out_at: string | null
          phone: string
          region: string | null
        }
        Insert: {
          apartment_id?: string | null
          consent_at?: string
          consent_source?: string
          created_at?: string
          gu?: string | null
          id?: number
          last_notified_at?: string | null
          notify_count?: number
          opt_out_at?: string | null
          phone: string
          region?: string | null
        }
        Update: {
          apartment_id?: string | null
          consent_at?: string
          consent_source?: string
          created_at?: string
          gu?: string | null
          id?: number
          last_notified_at?: string | null
          notify_count?: number
          opt_out_at?: string | null
          phone?: string
          region?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "subscribers_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: false
            referencedRelation: "apartments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscribers_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: false
            referencedRelation: "apartments_flat"
            referencedColumns: ["id"]
          },
        ]
      }
      trade_stats: {
        Row: {
          apartment_id: string
          avg_floor: number | null
          cancel_ratio_6m: number | null
          floor_range: string | null
          jeonse_by_area: Json | null
          jeonse_rate: number | null
          nearby_build_year: number | null
          nearby_median: number | null
          pir: number | null
          price_by_area: Json | null
          price_by_floor: Json | null
          psr: number | null
          recent_trades_6m: number | null
          rent_by_area: Json | null
          updated_at: string | null
        }
        Insert: {
          apartment_id: string
          avg_floor?: number | null
          cancel_ratio_6m?: number | null
          floor_range?: string | null
          jeonse_by_area?: Json | null
          jeonse_rate?: number | null
          nearby_build_year?: number | null
          nearby_median?: number | null
          pir?: number | null
          price_by_area?: Json | null
          price_by_floor?: Json | null
          psr?: number | null
          recent_trades_6m?: number | null
          rent_by_area?: Json | null
          updated_at?: string | null
        }
        Update: {
          apartment_id?: string
          avg_floor?: number | null
          cancel_ratio_6m?: number | null
          floor_range?: string | null
          jeonse_by_area?: Json | null
          jeonse_rate?: number | null
          nearby_build_year?: number | null
          nearby_median?: number | null
          pir?: number | null
          price_by_area?: Json | null
          price_by_floor?: Json | null
          psr?: number | null
          recent_trades_6m?: number | null
          rent_by_area?: Json | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "trade_stats_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: true
            referencedRelation: "apartments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trade_stats_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: true
            referencedRelation: "apartments_flat"
            referencedColumns: ["id"]
          },
        ]
      }
      trades: {
        Row: {
          apt_name: string | null
          area: number | null
          build_year: number | null
          cancel_date: string | null
          deal_month: string | null
          dealing_type: string | null
          deposit: number | null
          dong: string | null
          floor: number | null
          gu: string | null
          id: number
          price: number | null
          recorded_at: string
          region: string
          trade_type: string | null
        }
        Insert: {
          apt_name?: string | null
          area?: number | null
          build_year?: number | null
          cancel_date?: string | null
          deal_month?: string | null
          dealing_type?: string | null
          deposit?: number | null
          dong?: string | null
          floor?: number | null
          gu?: string | null
          id?: number
          price?: number | null
          recorded_at?: string
          region: string
          trade_type?: string | null
        }
        Update: {
          apt_name?: string | null
          area?: number | null
          build_year?: number | null
          cancel_date?: string | null
          deal_month?: string | null
          dealing_type?: string | null
          deposit?: number | null
          dong?: string | null
          floor?: number | null
          gu?: string | null
          id?: number
          price?: number | null
          recorded_at?: string
          region?: string
          trade_type?: string | null
        }
        Relationships: []
      }
      transport: {
        Row: {
          apartment_id: string
          bus_routes: number | null
          bus_stop_names: string | null
          ic_dist: number | null
          ktx_dist: number | null
          subway_dist: number | null
          subway_lines: string | null
          subway_name: string | null
          updated_at: string | null
        }
        Insert: {
          apartment_id: string
          bus_routes?: number | null
          bus_stop_names?: string | null
          ic_dist?: number | null
          ktx_dist?: number | null
          subway_dist?: number | null
          subway_lines?: string | null
          subway_name?: string | null
          updated_at?: string | null
        }
        Update: {
          apartment_id?: string
          bus_routes?: number | null
          bus_stop_names?: string | null
          ic_dist?: number | null
          ktx_dist?: number | null
          subway_dist?: number | null
          subway_lines?: string | null
          subway_name?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "transport_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: true
            referencedRelation: "apartments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transport_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: true
            referencedRelation: "apartments_flat"
            referencedColumns: ["id"]
          },
        ]
      }
      unsold_history: {
        Row: {
          apartment_id: string
          base_month: string
          change: number | null
          id: number
          post_completion_unsold: number | null
          recorded_at: string
          unsold_count: number | null
        }
        Insert: {
          apartment_id: string
          base_month: string
          change?: number | null
          id?: number
          post_completion_unsold?: number | null
          recorded_at?: string
          unsold_count?: number | null
        }
        Update: {
          apartment_id?: string
          base_month?: string
          change?: number | null
          id?: number
          post_completion_unsold?: number | null
          recorded_at?: string
          unsold_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "unsold_history_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: false
            referencedRelation: "apartments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "unsold_history_apartment_id_fkey"
            columns: ["apartment_id"]
            isOneToOne: false
            referencedRelation: "apartments_flat"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          approved_until: string | null
          created_at: string
          daily_crawl_quota: number
          daily_export_quota: number
          daily_price_collect_quota: number | null
          display_name: string | null
          email: string
          last_login_at: string | null
          login_count: number
          role: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          approved_until?: string | null
          created_at: string
          daily_crawl_quota: number
          daily_export_quota: number
          daily_price_collect_quota?: number | null
          display_name?: string | null
          email: string
          last_login_at?: string | null
          login_count: number
          role: string
          status: string
          updated_at: string
          user_id: string
        }
        Update: {
          approved_until?: string | null
          created_at?: string
          daily_crawl_quota?: number
          daily_export_quota?: number
          daily_price_collect_quota?: number | null
          display_name?: string | null
          email?: string
          last_login_at?: string | null
          login_count?: number
          role?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      apartments_flat: {
        Row: {
          address: string | null
          airQuality: Json | null
          announcementUrl: string | null
          area: number | null
          avgFloor: number | null
          avgMaintenanceCost: number | null
          avgPriceSqm: number | null
          balconyFree: boolean | null
          balconyValue: number | null
          bank: number | null
          bankDist: number | null
          benefits: Json | null
          builder: string | null
          builderCreditGrade: string | null
          builderDebtRatio: number | null
          buildingCoverageRatio: number | null
          busRoutes: number | null
          busStopNames: string | null
          cafe: number | null
          cafeDist: number | null
          cancelRatio6m: number | null
          cashback: number | null
          catsCache: Json | null
          childcare: number | null
          childcareDist: number | null
          cityDev: string | null
          competitionApplicants: number | null
          competitionRate: number | null
          competitionSupply: number | null
          completion: string | null
          contractDiscount: boolean | null
          conv: number | null
          convDist: number | null
          corridorType: string | null
          crimeSafetyGrade: number | null
          culture: number | null
          cultureDist: number | null
          dataReliability: number | null
          devDist: number | null
          discountPct: number | null
          district: string | null
          dong: string | null
          dsr40pass: boolean | null
          elecUsageKwh: number | null
          emergency: number | null
          emergencyDist: number | null
          energyCollectedAt: string | null
          energyGrade: number | null
          exclusiveRatio: number | null
          floorAreaRatio: number | null
          floorRange: string | null
          floors: string | null
          gasUsageMj: number | null
          greenBldg: string | null
          gu: string | null
          hasPool: boolean | null
          heatFuel: string | null
          heating: string | null
          hospital: number | null
          hospitalDist: number | null
          hugGuarantee: boolean | null
          icDist: number | null
          id: string | null
          industryDev: string | null
          initialSaleRate: number | null
          isRegulated: boolean | null
          jeonseByArea: Json | null
          jeonseRate: number | null
          ktxDist: number | null
          landCostRatio: number | null
          lastUnsoldEventAt: string | null
          lat: number | null
          layout: string | null
          lng: number | null
          loanFree: boolean | null
          loanFreePct: number | null
          mart: number | null
          martDist: number | null
          maxFloor: number | null
          name: string | null
          naverAvgFloor: number | null
          naverBuildYear: number | null
          naverFetchedAt: string | null
          naverJeonseCount: number | null
          naverJeonseRate: number | null
          naverNearbyAvg: number | null
          naverNearbyCount: number | null
          naverNearbyMedian: number | null
          naverPresaleNo: string | null
          naverPresaleSeq: string | null
          naverSchoolWalkMin: number | null
          naverSellCount: number | null
          naverWolseCount: number | null
          nearbyBuildYear: number | null
          nearbyFacilities: Json | null
          nearbyMedian: number | null
          nearbySchools: Json | null
          netMigration: number | null
          newSupply: number | null
          noise: number | null
          noxious: Json | null
          noxiousDist: number | null
          optionFree: boolean | null
          optionValue: number | null
          park: number | null
          parkDist: number | null
          parkingRatio: number | null
          pharmacy: number | null
          pharmacyDist: number | null
          pir: number | null
          police: number | null
          policeDist: number | null
          popGrowth: number | null
          pp: number | null
          presaleBuildings: number | null
          presaleFeatures: string | null
          presaleFetchedAt: string | null
          presaleGeneralSupply: number | null
          presaleHousingType: string | null
          presaleImageUrl: string | null
          presaleInquiry: string | null
          presaleMaxPrice: number | null
          presaleMinPrice: number | null
          presaleMoveIn: string | null
          presaleParking: number | null
          presalePp: number | null
          presaleRecruitDate: string | null
          presaleSchedule: Json | null
          presaleStage: string | null
          presaleStageCode: string | null
          presaleType: string | null
          price: number | null
          priceByArea: Json | null
          priceByFloor: Json | null
          priceIndex: number | null
          primaryDirection: string | null
          psr: number | null
          quakeDesign: boolean | null
          recentTrades6m: number | null
          region: string | null
          rentByArea: Json | null
          roadAddress: string | null
          schoolGrade: string | null
          schoolScore: number | null
          scoresComputedAt: string | null
          subwayDist: number | null
          subwayLines: string | null
          subwayName: string | null
          sunlight: string | null
          supplyRatio: number | null
          transitDev: string | null
          units: number | null
          unsold: number | null
          unsoldEventCount: number | null
          unsoldRate: number | null
          updatedAt: string | null
          view: string | null
        }
        Relationships: []
      }
      api_quota_daily: {
        Row: {
          api_name: string | null
          collector_count: number | null
          collectors: string | null
          log_date: string | null
          total_calls: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
